# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQB0Cdux-7gmugV1oaCtmML4dOaOf1cd
"""

from fastapi import FastAPI
from pydantic import BaseModel

import pickle
import numpy as np

hasil = response.json()

st.success(f"Prediction : {hasil['prediction']}")
st.metric("Probability", f"{hasil['probability']:.2%}")

class InputData(BaseModel):

    features:list

@app.get("/")
def home():

    return {"status":"SVM API Running"}

@app.post("/predict")
def predict(data:InputData):

    x=np.array(data.features).reshape(1,-1)

    x=scaler.transform(x)

    prediction=model.predict(x)[0]

    probability=model.predict_proba(x).max()

    return{

        "prediction":int(prediction),
        "probability":float(probability)

    }
